plugins = []
headers = []

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]

[functions."*"]

[build]
publish = "/opt/build/repo/artifacts/feed-the-homies/dist/public"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm --filter @workspace/feed-the-homies... run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]